# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install NodeJS
        run: apt install nodejs
      # Json validation
      - uses: actions/checkout@v3
      - name: Validate JSON
        uses: OrRosenblatt/validate-json-action@0.1.0
        with:
          json:  ./themes/GREY-BLUE DARKNESS-color-theme.json
      - name: Install requries packages
        run: npm install -g vsce

      - name: vsce login grey-bluedarkness
        run: |
          vsce login grey-bluedarkness
          {{ secrets.TOKEN }}

      - name: vsce package and publish
        run: |
          vsce package
          vsce publish
          echo "DONE!"